PKG_NAME=checkedc
PKG_URL=https://github.com/Microsoft/checkedc.git
PKG_VERSION=526661dd5d35e05acb13ec4d00255d79395cdffc
PKG_LICENSE=MIT

.PHONY: all

all: git-download

include $(RIOTBASE)/pkg/pkg.mk
