PKG_NAME=checkedc
PKG_URL=https://github.com/Microsoft/checkedc.git
PKG_VERSION=1768c2ae2aef912e514a788605497ea294f9622c
PKG_LICENSE=MIT

.PHONY: all

all: git-download

include $(RIOTBASE)/pkg/pkg.mk
