PKG_NAME=checkedc
PKG_URL=https://github.com/Microsoft/checkedc.git
PKG_VERSION=261aacbce9ce0adef633940e88702103e8aef3a6
PKG_LICENSE=MIT

.PHONY: all

all: git-download

include $(RIOTBASE)/pkg/pkg.mk
